name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps (ci)
        run: npm ci
        env:
          NPM_CONFIG_FUND: false
          NPM_CONFIG_AUDIT: false

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build Nuxt
        env:
          NUXT_TELEMETRY_DISABLED: 1
        run: npm run build
        
      - name: Upload .output
        if: ${{ always() && hashFiles('.output/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-output
          path: .output
