name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'        
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --run

      - name: Build
        run: NITRO_PRESET=github-pages npm run build

      - name: Upload static (optional)
        if: success() && hashFiles('.output/public/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: .output/public
